### ISSUE TITLE
Dockerfile misses alpine python and build-base packages to build

### ISSUE THREAD

**Issue by madageomapping** [yathindra123/recap#1]
I had added those lines to get the docker build succeeded : 

apk add python build-base gcc wget git 

Then, I launched the container with this command :

docker run --rm -p 0.0.0.0:8082:8082 recap

but when running the container, the app showed : 

http://127.0.0.1:8080
http://172.17.0.3:8080

despite of the command whithin the dockerfile : "EXPOSE 8082"

Finaly, as seen on the screenshot, the main page is not what i expected ..
![2019-01-03-143502_2720x900_scrot](https://user-images.githubusercontent.com/11469513/50635746-af581b80-0f53-11e9-98fa-4a5f63f06f34.png)

My question :+1: 
Have you a docker image of your app that I can use  ?

Regards

Thierry

**Comment by yathindrak** [comment]
Hi @madageomapping,
Sorry, currently not.
Since currently we aren't using this app with Docker and personally, I am using this with pm2 with the nodejs backend(https://github.com/yathindra123/recap-be).

Also, haven't tested with Docker. 

If possible, add a pull request with the changes you have done with DockerFile.
